# Linguagem Utilizada para Desenvolver a Aplicação                                                                                                                                                       
language: python                                                                                                                                                                                         

# Versão que a aplicação suporta.                                                                                                                                                                        
python:                                                                                                                                                                                                  
  - "3.7.9"                                                                                                                                                                                              

os: linux
dist: xenial

jobs:
  include:
    - stage: Unit Test

      name: "Testes Unitarios"
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - coverage run test.py || travis_terminate 1;


    - stage: Quality Gate

      name: "Teste de qualidade e Seguranca"
      install:
          - pip install flask flask-wtf coverage
      script:
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;
        - sonar-scanner || travis_terminate 1;
      addons:
        sonarcloud:
          organization: rafhainiveronezi
          token: ${SONAR_TOKEN}

    - stage: Deploy in Prod
      script: skip
      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab-rafhaini
        on:
          branch: main
