# Linguagem Utilizada para Desenvolver a Aplicação                                                                                                                                                       
language: python                                                                                                                                                                                         

# Versão que a aplicação suporta.                                                                                                                                                                        
python:                                                                                                                                                                                                  
  - "3.7.9"                                                                                                                                                                                              

os: linux
dist: xenial

jobs:
  include:
    - stage: Unit Test

      name: "Testes Unitarios"
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - coverage run test.py || travis_terminate 1;


    - stage: Quality Gate

      name: "Teste de qualidade e Seguranca"
      install:
          - pip install flask flask-wtf coverage
      script:
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;
        - sonar-scanner || travis_terminate 1;
      addons:
        sonarcloud:
          organization: rafhainiveronezi
          token: ${SONAR_TOKEN}

    - stage: Deploy in Homologacao
      name: "Executando deploy em ambiente de homologação"
      script:
        - curl devopslab-rafhaini.herokuapp.com || travis_terminate 1;
      deploy:
          provider: heroku
          strategy: api
          api_key: $HEROKU_API_KEY
          edge: true
          app: devopslab-rafhaini-stg
          on:
            branch: main

    - stage: Deploy in Producao
      name: "Executando deploy em ambiente produtivo"
      script: skip
      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab-rafhaini
        on:
          branch: main

notifications:
 slack:
  secure: W0/CxlQGCEFaTDdeDbjS4ojp6GAmuMC709tnGeyUBnSHtHvcdWCzSR3mvj9qMF7yjJMcG9f9iUQnt9a/fHBdLEkRe5Wmoo1PMzoPhsXcX5+k5Mx/HbotWUb5Dh37Jr5ih/81p6wYNrQ8fwqXQ2ubpn3eHehVQMK4dMml56VDlvw6anjTu4VKsXB4MTrGI44Tepk5eQRtuaqHcZPk8/L0vxZ/nyrQKSUlo2aCkuACe3Sef7y13swjyxKsm2RJWnWLH3YRSbURfjeVDzrWOd3vqV207SAC8gA3psSG3PUClIbhQeR5kQigyeHlnE6XLUasCe/MQNNCvj+txsMfSyQaN5Kqy0QZ0+3bjKmYMsBadXitPUbMPu98aTPcZ47gslAvxdABsWgMU39ixvBzXMtkHrKP33Ulgp5Xy5z2ce0VSai1SZNzGJSacWyUCIwa1ZNo7GaXCzsWDRnmcQDFjYr+lvaLBThIAstylB0jIgJdOt3vJJWwaqNQbQoYEUHSQmy4F8zLR26zw0ZquR8tOHWvIGho8sYvRFthJe724iGzn/j8j3EW99JOnjqrN0yiIjpL2whr7EYZGDq8ag+xGrSEo+7ZQcGP6QIuPwkYIYL8wbWcnumY38H0rBU0HilX3oMkb6LZvow9JUBgk5y/eTqXrjeI2haJ4zsvn7tO/4rrS8Q=
